"""add foreign keys

Revision ID: 44eabe92884c
Revises: c16ae68e479d
Create Date: 2026-03-19 21:46:50.992439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44eabe92884c'
down_revision: Union[str, Sequence[str], None] = 'c16ae68e479d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'guesses', 'games', ['game_id'], ['id'])
    op.alter_column('players', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'players', 'games', ['game_id'], ['id'])
    op.alter_column('statements', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'statements', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.alter_column('statements', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.alter_column('players', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'guesses', type_='foreignkey')
    # ### end Alembic commands ###
