"""add current_statement_id in games

Revision ID: 65ae1505fdb8
Revises: 294987c8d66f
Create Date: 2026-03-25 23:35:05.771289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ae1505fdb8'
down_revision: Union[str, Sequence[str], None] = '294987c8d66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('current_statement_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'current_statement_id')
    # ### end Alembic commands ###
