"""add host_forced_finish to games

Revision ID: 87fa62f2f68d
Revises: a70b7ce1ff1c
Create Date: 2026-04-06 07:05:19.234814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fa62f2f68d'
down_revision: Union[str, Sequence[str], None] = 'a70b7ce1ff1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('host_forced_finish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'host_forced_finish')
    # ### end Alembic commands ###
