"""add duration to games

Revision ID: 99ac5d918ccf
Revises: 87fa62f2f68d
Create Date: 2026-04-12 15:30:09.021829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ac5d918ccf'
down_revision: Union[str, Sequence[str], None] = '87fa62f2f68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('duration', sa.Integer(), nullable=True))
    op.execute("UPDATE games SET duration = 120 WHERE duration IS NULL")
    op.alter_column(
        "games",
        "duration",
        nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'duration')
    # ### end Alembic commands ###
