"""add round_started_at to games

Revision ID: a70b7ce1ff1c
Revises: 65ae1505fdb8
Create Date: 2026-03-31 20:21:36.998267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70b7ce1ff1c'
down_revision: Union[str, Sequence[str], None] = '65ae1505fdb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('round_started_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'round_started_at')
    # ### end Alembic commands ###
