"""add ended_at to games

Revision ID: b6d7a26e2ed2
Revises: 44eabe92884c
Create Date: 2026-03-25 19:29:55.870016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d7a26e2ed2'
down_revision: Union[str, Sequence[str], None] = '44eabe92884c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('ended_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ended_at')
    # ### end Alembic commands ###
